tn=int(input('Diagente um numero da tábuada:'))
print('_'*16)
print(f'{tn}x1={tn*1}')
print(f'{tn}x2={tn*2}')
print(f'{tn}x3={tn*3}')
print(f'{tn}x4={tn*4}')
print(f'{tn}x5={tn*5}')
print(f'{tn}x6={tn*6}')
print(f'{tn}x7={tn*7}')
print(f'{tn}x8={tn*8}')
print(f'{tn}x9={tn*9}')
print(f'{tn}x10={tn*10}')
print('_'*16)